# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: protoc-gen-procframe-go

before:
  hooks:
    - go mod download

builds:
  - id: protoc-gen-procframe-go
    main: ./cmd/protoc-gen-procframe-go
    binary: protoc-gen-procframe-go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/shuymn/procframe/internal/version.Version={{ .Version }}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - third_party_licenses/*

checksum:
  name_template: checksums.txt

changelog:
  disable: true

release:
  draft: true
