package codegen

import (
	"google.golang.org/protobuf/compiler/protogen"
)

// generateHandler writes the *.handler.proc.go file for a service,
// producing a handler interface with one method per RPC.
func generateHandler(plugin *protogen.Plugin, file *protogen.File, svc *protogen.Service) {
	filename := file.GeneratedFilenamePrefix + ".handler.proc.go"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-procframe-go. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	g.P("// ", svc.GoName, "Handler is the handler interface for ", svc.GoName, ".")
	g.P("type ", svc.GoName, "Handler interface {")

	for _, m := range svc.Methods {
		if m.Desc.IsStreamingServer() {
			g.P("\t", m.GoName, "(")
			g.P("\t\t", contextPkg.Ident("Context"), ",")
			g.P("\t\t*", procframePkg.Ident("Request"), "[", m.Input.GoIdent, "],")
			g.P("\t\t", procframePkg.Ident("ServerStream"), "[", m.Output.GoIdent, "],")
			g.P("\t) error")
		} else {
			g.P("\t", m.GoName, "(")
			g.P("\t\t", contextPkg.Ident("Context"), ",")
			g.P("\t\t*", procframePkg.Ident("Request"), "[", m.Input.GoIdent, "],")
			g.P("\t) (*", procframePkg.Ident("Response"), "[", m.Output.GoIdent, "], error)")
		}
	}

	g.P("}")
}
